spring.application.name=oficinaMecanica-api2
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/cp1api2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=cp1user
spring.datasource.password=cp1pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/
